### PR TITLE
F/qualtest

### PR DESCRIPTION
**Pull request by vitiral**
These are features that are necessary for running the qual test efficiently. Most of them are convenience functions, but they significantly aid in testing and utilizing the library.

I want to write more tests to make sure the `create` methods work when an instance exists, but I need the properties branch merged first to get access to the mock_instance creator.

### CODE REVIEW

**Comment by cloudformdesign** [comment]
the referential imports above is going to affect all tests as it affects imports from pynio, but it is the correct way to do things.

**Comment by cloudformdesign** [comment]
DON'T MERGE THIS UNTIL PROPERTIES IS MERGED

Then I will merge master into this and then notify you

**Comment by cloudformdesign** [comment]
All tests are passing after merge with master

**Comment by hansmosh** [comment]
Can we close this PR?

**Comment by cloudformdesign** [comment]
Ya,  keep the branch for now

**Comment by hansmosh** [comment]
Closing the PR but keeping the branch. Most of the relevant features from this PR have been merged to master already.

**Pull request closed without merging**
