### PR TITLE
use getitem  instead of .get to prevent errors from passing

### PR DESCRIPTION
**Pull request by vitiral**

### CODE REVIEW

**Comment by hansmosh** [comment]
I'm not seeing the purpose of this. Why do you ever want exceptions to be raised in these situations?

**Comment by cloudformdesign** [comment]
because I don't want to be getting improper names.

**Comment by cloudformdesign** [comment]
For instance `if blk.get('name') == blk1.name` will return None if you accidentally did: 

`if blk.get('nam') == blk1.name`

Or if you changed it from 'name' to 'block_name' or anything else.

Worse yet, it would just evaluate to False and you wouldn't know why

**Comment by hansmosh** [comment]
The only reason any of those dictionary keys wouldn't exist is if the config coming from the nio REST api has an unexpected value. First of all, it's bad either way if that happens so this debate is sort of for something that should never happen anyway. Second, I think it's better for pynio to smoothly continue in case of some strange config values. And if you disagree and want Exceptions to be raised here, a KeyError isn't a particularly useful one.

**Comment by cloudformdesign** [comment]
If this is never supposed to happen it doesn't matter what kind of error is
raised.

From the Zen "Although practicality beats purity. Errors should never pass
silently. Unless explicitly silenced."

Most of these errors would only happen if something was going terribly
wrong in our `connect` method itself (or if the user decided to manually
add their own connections). The API one shouldn't happen and probably won't
happen,  but if it DID happen I would want to know and replace it with a
better error

It's just a bad idea to let errors that should never happen pass silently.
That will cause undefined behavior

**Comment by cloudformdesign** [comment]
Also,  dic[item] is the standard way to get an item from a dictionary.  I'm
confused as to why we would use a method whose purpose is to ignore key
errors,  when key errors should never happen.

- sent from my Android

**Pull request merged**
